import { normalizeSkillText } from "@/lib/skills/normalize";
import type { ChildSkillSpec } from "@/lib/roadmap-visual/skills-spec";
import type { TemplateSpec } from "@/lib/roadmap-visual/template-spec";
import type { RoadmapAnswer } from "./model";

/** lowercase, dashes: the stable node key for a topic, derived from its skill so a regenerated roadmap keeps the same keys (and the student's marks). */
export const slug = (text: string): string => text.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 80);
export const skillKeyFor = (name: string): string => `SKILL_${name.toUpperCase().replace(/[^A-Z0-9]+/g, "_").replace(/^_+|_+$/g, "").slice(0, 80)}`;

export const PROVENANCE_METHOD =
  "Generated by an AI model from the canonical skill taxonomy, then machine validated (every skill exists, structure, no cycles, stage order). Not reviewed by a person.";

/** Pure. New skills the model asked for, minus any whose name already exists, keyed deterministically. */
export function childSkillsFrom(answer: RoadmapAnswer, existingNames: ReadonlySet<string>): ChildSkillSpec[] {
  const known = new Set([...existingNames].map(normalizeSkillText));
  const seen = new Set<string>();
  const out: ChildSkillSpec[] = [];
  for (const s of answer.newSkills) {
    const n = normalizeSkillText(s.name);
    if (known.has(n) || seen.has(n)) continue;
    seen.add(n);
    out.push({ key: skillKeyFor(s.name), name: s.name.trim(), parent: s.parent, description: s.description.trim() });
  }
  return out;
}

/**
 * Pure. The model's answer as a TemplateSpec. Topic keys are rewritten to slug(skill) (edges follow), so keys never depend on the model's mood;
 * group and stage keys are kept as given. Anything the validator rejects afterwards is reported back to the model as feedback.
 */
export function toTemplateSpec(answer: RoadmapAnswer, ctx: { careerKey: string; version: number; model: string }): TemplateSpec {
  const rename = new Map<string, string>();
  const used = new Set(answer.nodes.filter((n) => n.type !== "TOPIC").map((n) => n.key));
  for (const n of answer.nodes) {
    if (n.type !== "TOPIC" || !n.skill) continue;
    let key = slug(n.skill) || n.key;
    while (used.has(key)) key = `${key}-x`;
    used.add(key);
    rename.set(n.key, key);
  }
  const k = (key: string) => rename.get(key) ?? key;
  return {
    career: ctx.careerKey,
    version: ctx.version,
    title: answer.title,
    ...(answer.description ? { description: answer.description } : {}),
    provenance: { designedBy: `AI (${ctx.model})`, method: PROVENANCE_METHOD },
    nodes: answer.nodes.map((n) => ({ ...n, key: k(n.key), parent: n.parent ? k(n.parent) : null })),
    edges: answer.edges.map((e) => ({ ...e, from: k(e.from), to: k(e.to) })),
  };
}

export const MIN_TOPICS = 20;
export const MIN_STAGES = 3;

/** Pure. Quality gates beyond structural validity: a roadmap with a handful of topics is not a roadmap. */
export function qualityErrors(spec: TemplateSpec): string[] {
  const topics = spec.nodes.filter((n) => n.type === "TOPIC");
  const errors: string[] = [];
  if (topics.length < MIN_TOPICS) errors.push(`Only ${topics.length} topics: a career roadmap needs at least ${MIN_TOPICS}.`);
  const stages = new Set(spec.nodes.filter((n) => n.type === "SPINE").map((n) => n.stage));
  if (stages.size < MIN_STAGES) errors.push(`Only ${stages.size} stage(s) used: spread the roadmap across at least ${MIN_STAGES} of FOUNDATION, CORE, SPECIALIZATION, JOB_READY.`);
  return errors;
}
