export interface CapabilitySnapshot {
  skill: string;
  score: number;
  confidence: "low" | "medium" | "high";
}

export interface SkillGap {
  skill: string;
  required: number;
  current: number | null;
  confidence: "low" | "medium" | "high" | "unassessed";
  gap: number;
}

export type CareerRecommendation = "Ready" | "Explore" | "Long-term pathway";

export interface CareerMatch {
  careerRole: string;
  interestLevel: number;
  overallReadiness: number;
  skillGaps: SkillGap[];
  recommendation: CareerRecommendation;
}

// Deterministic thresholds — the numbers here are never generated by AI.
// Recommendation is driven by readiness (inverse of average gap), not
// interest alone: high interest + large gap is "Long-term pathway", not
// "Ready", per the brief's insistence that interest and capability stay
// separate signals.
const READY_THRESHOLD = 85;
const EXPLORE_THRESHOLD = 60;

/** Pure function: required capabilities vs current — no AI involved. */
export function computeSkillGaps(
  requirements: Record<string, number>,
  capabilities: CapabilitySnapshot[]
): SkillGap[] {
  const bySkill = new Map(capabilities.map((c) => [c.skill, c]));
  return Object.entries(requirements).map(([skill, required]) => {
    const current = bySkill.get(skill);
    if (!current) {
      return { skill, required, current: null, confidence: "unassessed" as const, gap: required };
    }
    return {
      skill,
      required,
      current: current.score,
      confidence: current.confidence,
      gap: Math.max(0, required - current.score),
    };
  });
}

function overallReadiness(gaps: SkillGap[]): number {
  if (gaps.length === 0) return 0;
  const totalRequired = gaps.reduce((sum, g) => sum + g.required, 0);
  const totalAchieved = gaps.reduce((sum, g) => sum + Math.min(g.required, g.current ?? 0), 0);
  return Math.round((totalAchieved / totalRequired) * 100);
}

function classify(readiness: number): CareerRecommendation {
  if (readiness >= READY_THRESHOLD) return "Ready";
  if (readiness >= EXPLORE_THRESHOLD) return "Explore";
  return "Long-term pathway";
}

export function buildCareerMatch(
  careerRole: string,
  requirements: Record<string, number>,
  capabilities: CapabilitySnapshot[],
  interestLevel: number
): CareerMatch {
  const skillGaps = computeSkillGaps(requirements, capabilities);
  const readiness = overallReadiness(skillGaps);
  return {
    careerRole,
    interestLevel,
    overallReadiness: readiness,
    skillGaps,
    recommendation: classify(readiness),
  };
}
