-- Roadmaps, projects and certifications can be generated by the AI pipeline (lib/roadmap-generate). Nothing generated is trusted blindly:
-- the pipeline machine-validates every roadmap (canonical skills, no cycles, ...) and verifies every certification link before saving.
-- A generated roadmap has no human reviewer, so it is marked source = 'AI_GENERATED' instead of claiming a review that did not happen.

alter table public.roadmap_templates drop constraint if exists roadmap_templates_source_check;
alter table public.roadmap_templates add constraint roadmap_templates_source_check
  check (source in ('CAPABILIO', 'AI_DRAFTED_THEN_REVIEWED', 'AI_GENERATED'));

alter table public.roadmap_templates drop constraint if exists roadmap_templates_review_required;
alter table public.roadmap_templates add constraint roadmap_templates_review_required
  check (status in ('DRAFT', 'RETIRED') or reviewed_by is not null or source = 'AI_GENERATED');

-- Career-wide AI projects (not the per-student 'AI_GENERATED' recommendations, which keep their own rules).
alter table public.project_catalog drop constraint if exists project_catalog_source_check;
alter table public.project_catalog add constraint project_catalog_source_check
  check (source in ('CAPABILIO', 'COLLEGE', 'MENTOR', 'AI_GENERATED', 'AI_CAREER'));

-- One row per generation attempt. The partial unique index lets only one run per career be in flight.
create table if not exists public.roadmap_generation_runs (
  id uuid primary key default gen_random_uuid(),
  career_id uuid not null references public.careers(id) on delete cascade,
  status text not null check (status in ('RUNNING', 'SUCCEEDED', 'FAILED')),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  template_id uuid references public.roadmap_templates(id) on delete set null,
  model text,
  error text,
  report jsonb
);
create unique index if not exists roadmap_generation_one_running on public.roadmap_generation_runs (career_id) where status = 'RUNNING';
create index if not exists roadmap_generation_career_started on public.roadmap_generation_runs (career_id, started_at desc);
alter table public.roadmap_generation_runs enable row level security; -- service role only: no policies
