-- LeetCode-style Stream challenges for IT students, generated by AI once per week (Sunday 00:00 IST) and served the same week.
-- Decision (product owner): these are published without manual review. Safety rests on code, not on a human: every test output is
-- produced by RUNNING a reference solution, and a second independent AI solution must reproduce every output before a problem is kept.
-- The review gate (arena_challenges_ai_must_be_reviewed) still applies to source 'AI_GENERATED'; the weekly set has its own source.
alter table public.arena_challenges drop constraint if exists arena_challenges_kind_check;
alter table public.arena_challenges add constraint arena_challenges_kind_check check (kind in ('code', 'numeric', 'sql', 'workstation', 'leetcode'));
alter table public.arena_challenges drop constraint if exists arena_challenges_source_check;
alter table public.arena_challenges add constraint arena_challenges_source_check check (source in ('CAPABILIO', 'COLLEGE', 'MENTOR', 'AI_GENERATED', 'AI_WEEKLY'));
alter table public.arena_challenges
  add column if not exists week_start date,
  /** student-visible problem: statement, formats, constraints, examples, starter code per language */
  add column if not exists problem jsonb;
create index if not exists arena_challenges_weekly on public.arena_challenges (scope_key, week_start) where kind = 'leetcode';

-- The judge's test cases (hidden ones included) and the reference solution. RLS on, no policies: service role only.
create table public.arena_challenge_tests (
  challenge_id uuid primary key references public.arena_challenges(id) on delete cascade,
  tests jsonb not null check (jsonb_typeof(tests) = 'array' and jsonb_array_length(tests) between 2 and 12),
  sample_count smallint not null check (sample_count between 1 and 4),
  reference_solution text not null,
  created_at timestamptz not null default now()
);
alter table public.arena_challenge_tests enable row level security;
revoke all on public.arena_challenge_tests from anon, authenticated;

-- One generation run per scope and week. A run that stops early is marked FAILED (or goes stale) and the next request or cron continues it.
create table public.arena_weekly_generation (
  scope_key text not null,
  week_start date not null,
  status text not null check (status in ('RUNNING', 'DONE', 'FAILED')),
  started_at timestamptz not null default now(),
  note text,
  primary key (scope_key, week_start)
);
alter table public.arena_weekly_generation enable row level security;
revoke all on public.arena_weekly_generation from anon, authenticated;
