-- Profile page: a cover image, headline, about and location a student edits themselves, plus the digital skill passport.
--  - passport_code: the unguessable id printed in the passport QR. Generated by the database, never writable by a client.
--  - passport_public: the student's own switch. The public passport page only answers while it is on (off by default).
-- Clients may only update the columns listed in the grant (see 031); the editable new ones are added to it.
alter table public.profiles
  add column if not exists cover_url text,
  add column if not exists headline text check (headline is null or char_length(headline) <= 120),
  add column if not exists bio text check (bio is null or char_length(bio) <= 600),
  add column if not exists location text check (location is null or char_length(location) <= 80),
  add column if not exists passport_code text not null default substr(replace(gen_random_uuid()::text, '-', ''), 1, 18),
  add column if not exists passport_public boolean not null default false;

create unique index if not exists profiles_passport_code_key on public.profiles (passport_code);

grant update (cover_url, headline, bio, location, passport_public) on public.profiles to authenticated;

-- The human-readable passport number (CAP-SWIFT-FALCON-7K2Q). Issued once by the server, never writable by a client, and unique:
-- the index is what guarantees no two students ever hold the same number.
alter table public.profiles add column if not exists passport_no text;
create unique index if not exists profiles_passport_no_key on public.profiles (passport_no);
